### ISSUE TITLE
scinv "_networkTypeFirewall" build error

### ISSUE THREAD

**Issue by filefolder** [SeisComP/main#40]
Trying to install master. Probably just bad timing on my part and this is already known but FWIW

```
Scanning dependencies of target scinv
[ 90%] Building CXX object src/base/main/apps/tools/inventory/scinv/CMakeFiles/scinv.dir/main.cpp.o
/Rdata/seiscomp/SRC/src/base/main/apps/tools/inventory/scinv/main.cpp: In member function 'virtual bool InventoryManager::validateParameters()':
/Rdata/seiscomp/SRC/src/base/main/apps/tools/inventory/scinv/main.cpp:499:4: error: '_networkTypeFirewall' was not declared in this scope
  499 |    _networkTypeFirewall = Util::StringFirewall();
      |    ^~~~~~~~~~~~~~~~~~~~
/Rdata/seiscomp/SRC/src/base/main/apps/tools/inventory/scinv/main.cpp:500:4: error: '_stationTypeFirewall' was not declared in this scope
  500 |    _stationTypeFirewall = Util::StringFirewall();
      |    ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/base/main/apps/tools/inventory/scinv/CMakeFiles/scinv.dir/build.make:63: src/base/main/apps/tools/inventory/scinv/CMakeFiles/scinv.dir/main.cpp.o] Error 1
```

**Comment by gempa-jabe** [comment]
Which OS is that? Our builds work and the last nightly is from July, 1st. Example: https://data.gempa.de/packages/Public/seiscomp/nightly/rhel/7/x86_64/.

**Comment by filefolder** [comment]
sorry should have mentioned

```
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

this is just the latest git pull as of now. python3.8 and gcc7.  

it does seem to work on another ubuntu 20.04.03 machine with python3.9 and gcc9, however.

**Comment by gempa-jabe** [comment]
OK, so gcc 7 seems to be an issue? Have you downgraded it? My Ubuntu 20.04 ships with gcc 9.4.0. Anyway, in master it should read:

```
_settings.networkTypeFirewall = ...
```

So you seems to run your build on outdated source code. Are you sure that all of your repositories are on latest master branch, especially `common`?

**Comment by filefolder** [comment]
I suspect the config was outdated; gcc9 is present but some settings were still pointing to say, g++ 7 etc. 

Currently attempting a fresh install to see if that fixes it, sounds like it should. TBA

**Comment by gempa-jabe** [comment]
Still, the error message points to the wrong source code ... let's see.

**Comment by filefolder** [comment]
yep you're right. not sure what happened but I had not updated the code since early version 4 days so possibly something had gone awry. 

a full wipe and re-clone has now given me the correct code. thanks for your help!
